
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Actividad1_proyecto(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);


//=======================================================
//  REG/WIRE declarations
//=======================================================
   wire [31:0] bus_32;


//=======================================================
//  Structural coding
//=======================================================
	assign LEDR[0] = SW[0] & SW[1];
	assign LEDR[1] = SW[2] | SW[3];
	assign LEDR[2] = ~(SW[0] & SW[1]);
	
	temporizador t1(
		.reloj(CLOCK_50),
		.salida(bus_32)
		);
		
	Multiplexor m1(
		.data0x(bus_32[31:28]),
		.data1x(bus_32[27:24]),
		.sel(SW[4]),
		.result(LEDR[9:6])
		);


endmodule